---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: helm_repository_apt_key [[[
#
# Helm APT repository GPG key
helm_repository_apt_key: https://baltocdn.com/helm/signing.asc

                                                                   # ]]]
# .. envvar:: helm_repository_url [[[
#
# Helm APT repository URL
helm_repository_url: https://baltocdn.com/helm/stable/debian/

                                                                   # ]]]
# .. envvar:: helm_version [[[
#
# Helm version to use
helm_version: 3.8.0

                                                                   # ]]]
