---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: ceph_osd_mons_group [[[
#
# Name of Ansible group that contains all Ceph monitors
ceph_osd_mons_group: controllers

                                                                   # ]]]
